# Generated by Django 3.2.12 on 2022-02-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='altitude',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='date_taken',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='latitude',
            field=models.DecimalField(decimal_places=97, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='longitude',
            field=models.DecimalField(decimal_places=47, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Choose a photo'),
        ),
    ]
